---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      name: memcached
      labels:
        name: memcached
        app: memcached
    spec:
      containers:
      - name: memcached
        image: frodenas/memcached
        imagePullPolicy: IfNotPresent
        env:
        - name: MEMCACHED_USERNAME
          value: "memcache"
        - name: MEMCACHED_PASSWORD
          value: "123123"
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: development
  labels:
    app: memcached
spec:
  type: NodePort
  selector:
    app: memcached
  ports:
  - port: 11211
    targetPort: 11211
    nodePort: 32161
    protocol: TCP
