apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: development
data:
  mysql.config：|
    user: mysql
    database: edukt
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: development
data:
  root_password: MTIzNDU2Cg==
  user_password: MTIzNDU2Cg==


