apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql56
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      name: mysql56
      labels:
        name: mysql56
        app: mysql56
    spec:
      containers:
      - name: mysql56
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123456
        - name: MYSQL_USER
          value: mysql
        - name: MYSQL_PASSWORD
          value: 123456
        ports:
        - name: TCP
          containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - hostPath:
          path: /opt/data/mysql
        name: data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql56
  namespace: development
  labels:
    app: mysql56
spec:
  type: NodePort
  selector:
    app: mysql56
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
