apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: platinst
data:
  username: mysql
  database: edukt
  mysql.config: |
    [mysqld]
    max_connections = 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: platinst
data:
  root_password: MTIzNDU2Cg==
  user_password: MTIzNDU2Cg==


