---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql56
  namespace: platinst
spec:
  replicas: 1
  template:
    metadata:
      name: mysql56
      labels:
        name: mysql56
        app: mysql56
    spec:
      nodeSelector:
        kubernetes.io/hostname: gd-node-01
      containers:
      - name: mysql56
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secrets
              key: root_password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: username
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secrets
              key: user_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        - mountPath: /etc/mysql/mysql.conf.d
          name: conf
      volumes:
      - hostPath:
          path: /opt/data/mysql
        name: data
      - hostPath:
          path: /opt/config/mysql
        name: conf
---
apiVersion: v1
kind: Service
metadata:
  name: mysql56
  namespace: platinst
  labels:
    app: mysql56
spec:
  type: NodePort
  selector:
    app: mysql56
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31277
    protocol: TCP
